"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";
import Image from "next/image";
import { AppSideBar } from "./ui/appsidebar";
import { AppNavBar } from "./ui/appnavbar";
import { AppFooter } from "./ui/appfooter";
import { Button } from "flowbite-react";
import { HiMenuAlt1 } from "react-icons/hi";
import { Suspense, useEffect, useState } from "react";
import { LayoutState } from "./interfaces/layoutstate"
import { Toaster } from "react-hot-toast";
import { Spinner } from "./ui/spinner";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isCollapsed, setCollapsed] = useState(true);

  const state: LayoutState = {
    isCollapsed,
    setCollapsed,
  };

  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        <Toaster position="top-center" toastOptions={{
          success: {
            duration:5000,
            style: {
              background:"#b8f6d0",
              width:"600px"
            }
          },
          error: {
            style: {
              background:"#f8a6a7",
              width:"300px"
            }
          },
        }}/>
        <div className="w-full min-w-0 flex-auto">
          <AppNavBar {...state} />
          <div className="relative">
            <div className="lg:flex">
              <AppSideBar {...state} />
              <div className="w-full min-w-0">
                <div className="mx-auto p-4">
                  {/* <Suspense fallback={<Spinner isLoading />}> */}
                    {children}
                  {/* </Suspense> */}
                </div>
                <AppFooter />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}

